---
title: "Case Study"
author: "Linze Yu"
date: "`r Sys.Date()`"
output:
  rmdformats::downcute:
    self_contained: TRUE
    default_style: "light"
    downcute_theme: "default"
    fig_width: 7
    fig_height: 5
    use_bookdown: TRUE
    gallery: TRUE
    lightbox: TRUE
    highlight: tango
editor_options: 
  markdown: 
    wrap: 72
---

```{r, 代码全局设置, echo = F}
knitr::opts_chunk$set(warning = F, error = F, message = F, prompt = T, comment = "", echo = T, dpi = 200, collapse = T, fig.align = "left", dev = "png", prompt = F, cache = T)
# , eval = F代码显示不运行
# , include = F代码运行, 不显示代码和结果
# , echo = T 显示代码块
# , prompt = T使用>开始代码
# , comment = ""结果不使用##
# , collapse = T#代码合并结果
# , out.width/out.height = 0.8缩放
# , fig.align = "left","center","right"对齐方式
# , dev = "pdf","png","svg","jpeg"记录设备
# , cache = T
```

## 加载包
```{r 加载包}
library("YuriR") #
library("ggbeeswarm") # 散点防止重合
library("ggExtra") # 边际直方图/密度曲线*
library("ggside") # 边际直方图/密度曲线
# library("ggwordcloud")#词云
# library("gghalves")#组合
```

# Case 1
```{r, echo = F, fig.width = 7, fig.height = 5}
import("D:/desktop/book/tidybook/data/prism1.xlsx") %>%
  longer_dt(name = "group", value = "value") %>%
  summarize_dt(n = .N, sd = sd(value), mean = mean(value), by = group) %>%
  ggplot(., aes(x = group, y = mean)) +
  geom_errorbar(aes(ymin = mean - sd / sqrt(n), ymax = mean + sd / sqrt(n)), color = 1, width = 0.25, size = 1, lineend = "square") +
  geom_col(color = NA, fill = "#95AAD3", alpha = 1, width = 0.5, size = 1, lineend = "square") +
  expand_limits(y = c(0, 14)) +
  scale_y_continuous(breaks = seq(0, 50, by = 2), minor_breaks = seq(0, 50, by = 1)) +
  labs(x = "", y = "N-cadherin relative expression(fold)", tag = "A") +
  Yuri_theme
```

```{r, eval = F}
theme(
  axis.title.y = element_text(size = 15, vjust = 0.5, hjust = 0.5, angle = 90, margin = margin(0, 3, 0, 0)),
  axis.text.x = element_text(vjust = 1, hjust = 1, angle = 45, margin = margin(1, 0, 0, 0)),
  panel.background = element_rect(color = NA, fill = NA),
  legend.background = element_rect(color = NA, fill = NA),
  legend.key = element_rect(color = NA, fill = NA),
  axis.line = element_line(color = "#96999C", size = 1, lineend = "square"),
  axis.ticks = element_line(color = "#96999C", size = 1),
  axis.ticks.length = unit(0.15, "cm"),
)
```

# Case 2
```{r, echo = F, fig.width = 7, fig.height = 5}
# col <- c("#BD3645", "#696AAD")
import("D:/desktop/book/tidybook/data/prism2.xlsx") %>%
  longer_dt(group1, name = "group", value = "value") %>%
  summarize_dt(group1, n = .N, sd = sd(value), mean = mean(value), by = group) %>%
  distinct_dt(.keep_all = T) %>%
  ggplot(., aes(x = group, y = mean, fill = group1)) +
  geom_errorbar(aes(ymin = mean - sd / sqrt(n), ymax = mean + sd / sqrt(n)), color = 1, width = 0.325, position = position_dodge(width = 0.65), size = 1, lineend = "square") +
  geom_col(color = NA, alpha = 1, width = 0.65, position = position_dodge2(width = 1.3), size = 1, lineend = "square") +
  scale_fill_manual(values = cols) +
  scale_y_continuous(breaks = seq(0, 50, by = 2), minor_breaks = seq(0, 50, by = 1)) +
  labs(x = "", y = "Relative luciferase activity(fold)", tag = "B") +
  Yuri_theme
```

```{r, eval = F}
theme(
  axis.title.y = element_text(size = 15, vjust = 0.5, hjust = 0.5, angle = 90, margin = margin(0, 3, 0, 0)),
  axis.text.x = element_text(vjust = 1, hjust = 1, angle = 45, margin = margin(1, 0, 0, 0)),
  panel.background = element_rect(color = NA, fill = NA),
  legend.background = element_rect(color = NA, fill = NA),
  legend.key = element_rect(color = NA, fill = NA),
  axis.line = element_line(color = "#96999C", size = 1, lineend = "square"),
  axis.ticks = element_line(color = "#96999C", size = 1),
  axis.ticks.length = unit(0.15, "cm"),
  legend.position = (c(0.15, 0.9))
)
```

# Case 3
```{r, echo = F, fig.width = 5, fig.height = 5}
import("D:/desktop/book/tidybook/data/prism3.xlsx") %>%
  longer_dt(n, name = "group", value = "value") %>%
  ggplot(., aes(x = group, y = value)) +
  geom_line(aes(group = n), alpha = 1, linetype = 1, color = "#96999C", lineend = "square") +
  expand_limits(y = c(0, 20)) +
  geom_point(shape = 21, size = 3, color = 1, fill = 1) +
  labs(x = "", y = "Relative miR-776-3p expression", title = "n=25 p<0.001") +
  Yuri_theme
```

```{r, eval = F}
theme(
  axis.title.y = element_text(size = 15, vjust = 0.5, hjust = 0.5, angle = 90, margin = margin(0, 3, 0, 0)),
  axis.text.x = element_text(vjust = 1, hjust = 1, angle = 45, margin = margin(1, 0, 0, 0)),
  panel.background = element_rect(color = NA, fill = NA),
  legend.background = element_rect(color = NA, fill = NA),
  legend.key = element_rect(color = NA, fill = NA),
  axis.line = element_line(color = 1, size = 0.5, lineend = "square"),
  axis.ticks = element_line(color = 1, size = 0.5),
  axis.ticks.length = unit(0.15, "cm"),
  plot.title = element_text(size = 15, hjust = 0.5, angle = 0, lineheight = 1, margin = margin(0, 1, 0, 0))
)
```

# Case 4
## 散点图
```{r}
import("D:/desktop/book/tidybook/data/case_1/0.xlsx") %>%
  ggplot(., aes(x = Adjacent, y = Tumor)) +
  geom_point(shape = 21, alpha = 0.5, color = "#696AAD", fill = "#95AAD3", stroke = 1, size = 5) +
  scale_x_continuous(breaks = seq(0, 20, by = 1), minor_breaks = seq(0, 0, by = 0)) +
  scale_y_continuous(breaks = seq(0, 20, by = 4), minor_breaks = seq(0, 0, by = 0)) +
  expand_limits(x = c(2, 6), y = c(0, 14)) +
  coord_fixed(ratio = 1 / 4) +
  Yuri_theme +
  labs(x = "Adjacent", y = "Tumor")
```

## 折线图
```{r}
import("D:/desktop/book/tidybook/data/case_1/1.xlsx") %>%
  longer_dt(., Day, name = "group", value = "value") %>%
  ggplot(., aes(x = Day, y = value, color = group, fill = group)) +
  stat_summary(fun.data = "mean_sd", geom = "point", size = 2, shape = 21, alpha = 0.5, stroke = 1, size = 4, fill = NA, lineend = "square") +
  stat_summary(fun.data = "mean_sd", geom = "errorbar", width = 0.3, alpha = 0.7, size = 1, lineend = "square") +
  stat_summary(fun.data = "mean_sd", geom = "line", alpha = 0.7, size = 1, lineend = "square") +
  scale_x_continuous(breaks = seq(0, 20, by = 1), minor_breaks = seq(0, 0, by = 0)) +
  scale_y_continuous(breaks = seq(0, 1200, by = 100), minor_breaks = seq(0, 0, by = 0)) +
  scale_color_manual(values = cols) +
  scale_fill_manual(values = fills) +
  coord_fixed(ratio = 2 / 200) +
  Yuri_theme +
  theme(legend.position = (c(0.4, 0.95))) +
  labs(x = "Day(s)", y = "Values")
```

## 柱状图1
```{r}
import("D:/desktop/book/tidybook/data/case_1/2.xlsx") %>%
  longer_dt(Replicates, name = "group", value = "value") %>%
  summarize_dt(n = .N, sd = sd(value), mean = mean(value), by = group) %>%
  ggplot(., aes(x = group, y = mean, color = group, fill = group)) +
  geom_errorbar(aes(ymin = mean - sd / sqrt(n), ymax = mean + sd / sqrt(n)), width = 0.25, alpha = 1, size = 1, lineend = "square") +
  geom_col(width = 0.5, alpha = 0.5, size = 1, lineend = "square") +
  scale_color_manual(values = cols) +
  scale_fill_manual(values = fills) +
  Yuri_theme +
  theme(legend.position = "none") +
  labs(x = "", y = "Values")
```

## 柱状图2
```{r}
import("D:/desktop/book/tidybook/data/case_1/3.xlsx") %>%
  longer_dt(Replicates, name = "group", value = "value") %>%
  summarize_dt(n = .N, sd = sd(value), mean = mean(value), by = group) %>%
  ggplot(., aes(x = group, y = mean, color = group, fill = group)) +
  geom_errorbar(aes(ymin = mean - sd / sqrt(n), ymax = mean + sd / sqrt(n)), width = 0.25, alpha = 1, size = 1, lineend = "square") +
  geom_col(width = 0.5, alpha = 0.5, size = 1, lineend = "square") +
  scale_color_manual(values = cols) +
  scale_fill_manual(values = fills) +
  scale_y_break(c(10, 100), scales = 0.25) +
  Yuri_theme +
  theme(legend.position = "none") +
  labs(x = "", y = "Values")
```

## 对比柱状图
```{r}
import("D:/desktop/book/tidybook/data/case_1/4.xlsx") %>%
  longer_dt(., name = "group2", value = "value") %>%
  ggplot(., aes(group2, value, color = group1, fill = group1)) +
  stat_summary(fun.data = "mean_sd", geom = "errorbar", width = 0.3, alpha = 1, position = position_dodge(width = 1), size = 1, lineend = "square") +
  stat_summary(fun.data = "mean_sd", geom = "col", width = 0.5, alpha = 0.5, position = position_dodge(width = 1), size = 1, lineend = "square") +
  scale_y_continuous(breaks = seq(0, 1500, by = 200), minor_breaks = seq(0, 0, by = 0)) +
  scale_color_manual(values = cols) +
  scale_fill_manual(values = fills) +
  Yuri_theme +
  theme(legend.position = (c(0.9, 0.9))) +
  labs(x = "", y = "Values")
```

## 生存曲线
```{r}
F <- import("D:/desktop/book/tidybook/data/case_1/5.xlsx")
fit <- survfit(Surv(Time_Months, Status) ~ Expression, data = F)
fit
p <- ggsurvplot(fit,
  data = F,
  fun = NULL,
  linetype = 1,
  conf.int = FALSE,
  pval = FALSE,
  pval.method = FALSE,
  test.for.trend = FALSE,
  surv.median.line = "hv",
  risk.table = FALSE,
  cumevents = FALSE,
  cumcensor = FALSE,
  tables.height = 0.25,
  legend = c(0.95, 0.95), # 指定图例位置
  facet.by = NULL,
  font.family = "Source Han Sans",
  ggtheme = Yuri_theme,
  add.all = FALSE,
  combine = FALSE
) +
  labs(x = "Time(Months)", y = "Cumsurvival(%)")
p
```

## 热图
```{r}
import("D:/desktop/book/tidybook/data/case_1/6.xlsx") %>%
  mutate_vars(2:3, scale) %>%
  longer_dt(ID, name = "group", value = "value") %>%
  ggplot(., aes(x = ID, y = group)) +
  geom_tile(alpha = 1, aes(fill = value)) +
  scale_fill_gradient(low = "#F8CDCD", high = "#696AAD") +
  expand_limits(x = c(1, 20), fill = seq(-2, 2, by = 1)) +
  scale_x_continuous(breaks = seq(1, 20, by = 2), minor_breaks = seq(0, 0, by = 0)) +
  Yuri_theme
```

# Case 5
## 散点图
```{r}
import("D:/desktop/book/tidybook/data/case_2/0.xlsx") %>%
  ggplot(., aes(x = X, y = Y)) +
  geom_point(size = 5, shape = 21, alpha = 0.5, color = "#696AAD", fill = "#95AAD3", stroke = 1) +
  coord_fixed(ratio = 1 / 1) +
  Yuri_theme
```

## 折线图
```{r}
import("D:/desktop/book/tidybook/data/case_2/1.xlsx") %>%
  longer_dt(., Day, name = "group", value = "value") %>%
  ggplot(., aes(Day, value, color = group, fill = group)) +
  stat_summary(fun.data = "mean_sd", geom = "point", size = 2, shape = 21, alpha = 0.7, stroke = 1, position = position_dodge(0.2), fill = NA, lineend = "square") +
  stat_summary(fun.data = "mean_sd", geom = "errorbar", width = 0.2, size = 0.8, alpha = 0.7, position = position_dodge(0.2), lineend = "square") +
  stat_summary(fun.data = "mean_sd", geom = "line", size = 1, alpha = 0.7, position = position_dodge(0.2), lineend = "square") +
  scale_color_manual(values = cols) +
  scale_fill_manual(values = fills) +
  coord_fixed(ratio = 1 / 1) +
  Yuri_theme +
  theme(legend.position = (c(0.35, 0.95)))
```

## 柱状图1
```{r}
import("D:/desktop/book/tidybook/data/case_2/2.xlsx") %>%
  longer_dt(., name = "group", value = "value") %>%
  summarize_dt(n = .N, sd = sd(value), mean = mean(value), by = group) %>%
  ggplot(., aes(x = reorder(group, -mean), y = mean, color = group, fill = group)) +
  geom_errorbar(aes(ymin = mean - sd / sqrt(n), ymax = mean + sd / sqrt(n)), width = 0.25, alpha = 1, size = 1, lineend = "square") +
  geom_col(width = 0.5, alpha = 0.5, size = 1, lineend = "square") +
  scale_y_continuous(breaks = seq(0, 2, by = 0.5), minor_breaks = seq(0, 0, by = 0)) +
  Yuri_theme +
  scale_color_manual(values = cols) +
  scale_fill_manual(values = fills) +
  theme(legend.position = ("none"))
```

## 对比柱状图
```{r}
import("D:/desktop/book/tidybook/data/case_2/3.xlsx") %>%
  longer_dt(., name = "group2", value = "value") %>%
  ggplot(., aes(group2, value, color = group1, fill = group1)) +
  stat_summary(fun.data = "mean_sd", geom = "errorbar", width = 0.5, size = 1, alpha = 1, position = position_dodge(width = 1), lineend = "square") +
  stat_summary(fun.data = "mean_sd", geom = "col", width = 0.8, size = 1, alpha = 0.5, position = position_dodge(width = 1), lineend = "square") +
  scale_y_continuous(breaks = seq(0, 5, by = 1), minor_breaks = seq(0, 0, by = 0)) +
  scale_color_manual(values = cols) +
  scale_fill_manual(values = fills) +
  Yuri_theme +
  theme(legend.position = (c(0.95, 0.95)))
```

## 箱线图
```{r}
import("D:/desktop/book/tidybook/data/case_2/4.xlsx") %>%
  longer_dt(., name = "group", value = "value") %>%
  ggplot(., aes(group, value, color = group, fill = group)) +
  geom_half_boxplot(alpha = 0.3, size = 0.618, position = position_nudge(x = 0, y = 0), side = "l", lineend = "square") +
  geom_half_violin(alpha = 0.3, size = 0.618, position = position_nudge(x = 0, y = 0), side = "r", trim = FALSE, lineend = "square") +
  scale_y_continuous(breaks = seq(-5, 5, by = 1), minor_breaks = seq(0, 0, by = 0)) +
  scale_color_manual(values = cols) +
  scale_fill_manual(values = fills) +
  Yuri_theme +
  theme(legend.position = ("none"))
```

## 生存曲线
```{r}
F <- import("D:/desktop/book/tidybook/data/case_2/5.xlsx")
fit <- survfit(Surv(Time_Months, Status) ~ Expression, data = F)
p <- ggsurvplot(fit, data = F, fun = NULL, linetype = 1, conf.int = FALSE, pval = FALSE, pval.method = FALSE, test.for.trend = FALSE, surv.median.line = "none", risk.table = FALSE, cumevents = FALSE, cumcensor = FALSE, tables.height = 0.25, facet.by = NULL, add.all = FALSE, combine = FALSE)
p
```

## 柱状图2
```{r}
import("D:/desktop/book/tidybook/data/case_2/6.xlsx") %>%
  longer_dt(., name = "group", value = "value") %>%
  summarize_dt(n = .N, sd = sd(value), mean = mean(value), by = group) %>%
  ggplot(., aes(group, mean, color = group, fill = group)) +
  geom_errorbar(aes(ymin = mean - sd / sqrt(n), ymax = mean + sd / sqrt(n)), width = 0.25, alpha = 1, size = 1, lineend = "square") +
  geom_col(width = 0.8, alpha = 0.5, size = 1, lineend = "square") +
  scale_color_manual(values = cols) +
  scale_fill_manual(values = fills) +
  Yuri_theme +
  theme(legend.position = ("none"))
```

## 热图
```{r}
import("D:/desktop/book/tidybook/data/case_2/7.xlsx") %>%
  mutate_vars(2:3, scale) %>%
  longer_dt(., ID, name = "Group", value = "value") %>%
  ggplot(., aes(x = ID, y = Group)) +
  geom_tile(alpha = 1, aes(fill = value)) +
  scale_fill_gradient(low = "#F8CDCD", high = "#696AAD") +
  expand_limits(x = c(1, 12), fill = seq(-2, 2, by = 1)) +
  scale_x_continuous(breaks = seq(1, 20, by = 2), minor_breaks = seq(0, 0, by = 0)) +
  Yuri_theme
```
